version: 0.0
os: linux
files:
  - source: MyApp-1.0-SNAPSHOT.war
    destination: /opt/tomcat/webapps/MyApp.war
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
