version: 0.0
os: linux
files:
  - source: /home/ubuntu/MyApp/target/MyApp-1.0-SNAPSHOT.war
    destination: /opt/tomcat/webapps/
    overwrite: true
    name: MyApp.war

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root

