name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Prepare deployment package
        run: |
          mkdir -p deploy/scripts
          cp target/MyApp-1.0-SNAPSHOT.war deploy/
          cp scripts/before-install.sh deploy/scripts/
          cp scripts/after-install.sh deploy/scripts/
          cp scripts/application-start.sh deploy/scripts/
          cp appspec.yml deploy/
          cd deploy
          zip -r MyApp.zip .

      - name: Upload to S3
        env:
          AWS_REGION: us-west-2
          S3_BUCKET: asgautodeploy
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp MyApp.zip s3://$S3_BUCKET/MyApp.zip --region $AWS_REGION

      - name: Deploy to AWS CodeDeploy
        env:
          AWS_REGION: us-west-2
          CODEDEPLOY_APP_NAME: javaapp
          CODEDEPLOY_DEPLOYMENT_GROUP: Asgdeploymentgrp
          S3_BUCKET: asgautodeploy
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP_NAME \
            --deployment-group-name $CODEDEPLOY_DEPLOYMENT_GROUP \
            --s3-location bucket=$S3_BUCKET,key=MyApp.zip,bundleType=zip \
            --region $AWS_REGION
