name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp target/*.war deploy/
          cp -r scripts/ deploy/
          cp appspec.yml deploy/
          cd deploy
          zip -r MyApp.zip .

      - name: Upload to GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: deploy/MyApp.zip

      - name: Deploy to AWS CodeDeploy
        env:
          AWS_REGION: us-west-2
          CODEDEPLOY_APP_NAME: javaapp
          CODEDEPLOY_DEPLOYMENT_GROUP: Asgdeploymentgrp
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP_NAME \
            --deployment-group-name $CODEDEPLOY_DEPLOYMENT_GROUP \
            --s3-location bucket=$S3_BUCKET,key=MyApp.zip,bundleType=zip \
            --region $AWS_REGION
